In [1]:
# bag of words = count of frequency of words in a string

In [22]:
with open('One.txt') as my_text:
    words_one = my_text.read().lower().split()
    uni_words_one = set(words_one)

In [23]:
uni_words_one

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'dogs',
 'furry',
 'is',
 'our',
 'pets',
 'story',
 'this'}

In [24]:
with open('Two.txt') as my_text:
    words_two = my_text.read().lower().split()
    uni_words_two = set(words_two)

In [25]:
uni_words_two

{'a',
 'about',
 'catching',
 'fun',
 'is',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [26]:
all_uni_word = set()
all_uni_word.update(uni_words_one)

In [27]:
all_uni_word.update(uni_words_two)

In [28]:
all_uni_word

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'catching',
 'dogs',
 'fun',
 'furry',
 'is',
 'our',
 'pets',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [29]:
full_vocab = dict()
i = 0

for word in all_uni_word:
    full_vocab[word] = i
    i = i + 1

In [30]:
full_vocab

{'about': 0,
 'pets': 1,
 'fun': 2,
 'catching': 3,
 'dogs': 4,
 'waves': 5,
 'story': 6,
 'animals': 7,
 'a': 8,
 'is': 9,
 'surfing': 10,
 'this': 11,
 'are': 12,
 'furry': 13,
 'water': 14,
 'popular': 15,
 'canine': 16,
 'sport': 17,
 'our': 18}

In [31]:
one_freq = [0] * len(full_vocab)
two_freq = [0] * len(full_vocab)
all_words = [''] * len(full_vocab)

In [33]:
two_freq

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [34]:
with open('One.txt') as f:
    one_text = f.read().lower().split()

In [35]:
one_text

['this',
 'is',
 'a',
 'story',
 'about',
 'dogs',
 'our',
 'canine',
 'pets',
 'dogs',
 'are',
 'furry',
 'animals']

In [36]:
for word in one_text:
    word_ind = full_vocab[word]
    one_freq[word_ind] += 1

In [37]:
one_freq

[1, 1, 0, 0, 2, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1]

In [38]:
with open('Two.txt') as f:
    two_text = f.read().lower().split()

In [39]:
for word in two_text:
    word_ind = full_vocab[word]
    two_freq[word_ind] += 1

In [40]:
two_freq

[1, 0, 1, 1, 0, 1, 1, 0, 1, 3, 2, 1, 0, 0, 1, 1, 0, 1, 0]

In [41]:
all_words

['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']

In [42]:
for word in full_vocab:
    word_ind = full_vocab[word]
    all_words[word_ind] = word

In [43]:
all_words

['about',
 'pets',
 'fun',
 'catching',
 'dogs',
 'waves',
 'story',
 'animals',
 'a',
 'is',
 'surfing',
 'this',
 'are',
 'furry',
 'water',
 'popular',
 'canine',
 'sport',
 'our']

In [44]:
import pandas as pd

In [46]:
bow = pd.DataFrame(data=[one_freq, two_freq], columns=all_words)

In [47]:
bow

about  pets  fun  catching  dogs  waves  story  animals  a  is  surfing  \
0      1     1    0         0     2      0      1        1  1   1        0   
1      1     0    1         1     0      1      1        0  1   3        2   

   this  are  furry  water  popular  canine  sport  our  
0     1    1      1      0        0       1      0    1  
1     1    0      0      1        1       0      1    0

In [59]:
text = ['This is a line',
        'This is another line',
        'Completely different line']

In [65]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

In [67]:
cv = CountVectorizer()

In [68]:
sparse_matrix = cv.fit_transform(text)

In [69]:
sparse_matrix.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]])

In [70]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [71]:
tfidf = TfidfTransformer()

In [72]:
sparse_matrix

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [73]:
results = tfidf.fit_transform(sparse_matrix)
# BOW ---> TF-IDF


In [74]:
results

<3x6 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [76]:
results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [77]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [78]:
tv = TfidfVectorizer()

In [80]:
tv_results = tv.fit_transform(text)

In [82]:
tv_results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])