In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [5]:
mylist

[1, 2, 3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [6]:
arr = np.array(mylist)

In [7]:
arr

array([1, 2, 3])

In [8]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
mymatrix = np.array(mylist)

In [12]:
mymatrix.shape

(3, 3)

In [15]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones((2,3)) + 4

array([[5., 5., 5.],
       [5., 5., 5.]])

In [23]:
np.ones(4) * 100

array([100., 100., 100., 100.])

In [24]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [25]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.random.rand(5,5)

array([[0.67829426, 0.64754755, 0.10644965, 0.84969746, 0.3227445 ],
       [0.70509865, 0.27399441, 0.98835634, 0.91893283, 0.10079189],
       [0.72265502, 0.35172374, 0.41116434, 0.82526274, 0.78006294],
       [0.16452704, 0.44603722, 0.69353926, 0.58577451, 0.04669398],
       [0.7508738 , 0.31314464, 0.39568909, 0.62981198, 0.10938542]])

In [30]:
np.random.rand(3)

array([0.83744115, 0.99782808, 0.37904935])

In [31]:
np.random.randn(1)

array([-1.44665076])

In [32]:
np.random.randn(10)

array([ 0.64799888, -0.94503546, -0.12863337,  0.27871494,  1.38269317,
        0.12978365, -0.72084235,  0.37877537,  0.73237004, -0.77548862])

In [33]:
np.random.normal(2)

2.4923553651273482

In [34]:
np.random.randint(1,100)

25

In [35]:
np.random.randint(1, 100, 10)

array([68, 25, 92, 13, 77, 37, 72, 37,  6, 82])

In [38]:
np.random.seed(101)

In [39]:
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [40]:
arr = np.arange(25)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
ranarr = np.random.randint(0,50,10)

In [43]:
ranarr

array([47,  9, 13, 40,  4, 40, 28,  0, 46,  5])

In [44]:
arr.shape

(25,)

In [45]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
ranarr

array([47,  9, 13, 40,  4, 40, 28,  0, 46,  5])

In [47]:
ranarr.max()

47

In [48]:
ranarr.min()

0

In [49]:
ranarr.argmax()

0

In [50]:
ranarr.argmin()

7

In [51]:
ranarr.dtype

dtype('int64')

In [52]:
arr = np.arange(0,11)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr[8]

8

In [55]:
arr[1:5]

array([1, 2, 3, 4])

In [56]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [57]:
arr[:5]

array([0, 1, 2, 3, 4])

In [58]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [59]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [61]:
new_arr = arr/2

In [62]:
new_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [63]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [64]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
slice_of_arr = arr[0:6]

In [66]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [67]:
slice_of_arr[:] = 99

In [68]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [69]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [70]:
arr_copy = arr.copy()

In [71]:
arr_copy[:] = 100

In [72]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [73]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

INDEXING ON 2D ARRAY

In [74]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [75]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [76]:
arr_2d[1]

array([20, 25, 30])

In [77]:
arr_2d[1][1]

25

In [78]:
arr_2d[1,1]

25

In [79]:
arr_2d[2,2]

45

In [80]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [84]:
arr = np.arange(1,11)

In [85]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [87]:
bool_array = arr > 4

In [88]:
bool_array

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [89]:
arr[bool_array]

array([ 5,  6,  7,  8,  9, 10])

In [90]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [91]:
arr[arr == 2]

array([2])

In [92]:
arr[arr >= 6]

array([ 6,  7,  8,  9, 10])

In [93]:
arr = np.arange(0,10)

In [94]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [95]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [96]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [97]:
(arr + 2) / 100

array([0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11])

In [99]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [100]:
1/arr

/Users/crisd/opt/anaconda3/envs/tsa_course/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [101]:
arr/arr

/Users/crisd/opt/anaconda3/envs/tsa_course/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [102]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [103]:
np.log(arr)

/Users/crisd/opt/anaconda3/envs/tsa_course/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [105]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [106]:
arr.sum()

45

In [107]:
arr.mean()

4.5

In [108]:
arr.max()

9

In [109]:
arr_2d = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [110]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [111]:
arr_2d.sum()

78

In [112]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [113]:
arr_2d.sum(axis=1)

array([10, 26, 42])